path = r'C:\Users\User\Desktop\USE AI_MalayalamAI_8 MAY 2026\backend\app\services\asr_service.py'

content = (
    "import os\n"
    "import re\n"
    "import numpy as np\n"
    "import tempfile\n"
    "import soundfile as sf\n"
    "from groq import Groq\n\n"
    "groq_client = Groq(api_key=os.environ.get('GROQ_API_KEY'))\n"
    "WHISPER_MODEL = 'whisper-large-v3'\n"
    "LLM_MODEL = 'llama-3.3-70b-versatile'\n"
    "DEVICE = 'groq-api'\n\n"
    "print(f'ASR ready: {WHISPER_MODEL} + {LLM_MODEL} via Groq API')\n\n"
    "LANG_NAMES = {'ml':'Malayalam','ta':'Tamil','te':'Telugu','kn':'Kannada','hi':'Hindi'}\n\n"
    "TRANSLATE_PROMPTS = {\n"
    "    'ml': 'You are an expert Malayalam-English translator. Translate the Malayalam text to natural English. Output ONLY English.',\n"
    "    'ta': 'You are an expert Tamil-English translator. Translate the Tamil text to natural English. Output ONLY English.',\n"
    "    'te': 'You are an expert Telugu-English translator. Translate the Telugu text to natural English. Output ONLY English.',\n"
    "    'kn': 'You are an expert Kannada-English translator. Translate the Kannada text to natural English. Output ONLY English.',\n"
    "    'hi': 'You are an expert Hindi-English translator. Translate the Hindi text to natural English. Output ONLY English.',\n"
    "}\n\n"
    "UNICODE_PROMPTS = {\n"
    "    'ml': 'You are a Malayalam expert. Write this text in natural Malayalam Unicode script (like: നമസ്കാരം). Output ONLY Malayalam characters, no English.',\n"
    "    'ta': 'You are a Tamil expert. Write this text in natural Tamil Unicode script (like: வணக்கம்). Output ONLY Tamil characters, no English.',\n"
    "    'te': 'You are a Telugu expert. Write this text in natural Telugu Unicode script (like: నమస్కారం). Output ONLY Telugu characters, no English.',\n"
    "    'kn': 'You are a Kannada expert. Write this text in natural Kannada Unicode script (like: ನಮಸ್ಕಾರ). Output ONLY Kannada characters, no English.',\n"
    "    'hi': 'You are a Hindi expert. Write this text in natural Hindi Devanagari script (like: नमस्ते). Output ONLY Hindi characters, no English.',\n"
    "}\n\n"
    "HALLUCINATIONS = [\n"
    "    'thank you for watching','thanks for watching','subscribe','music','[music]',\n"
    "    'subtitles','captions','hello and welcome','welcome to my channel',\n"
    "    'translated by','english is a language','language of the language',\n"
    "    \"i'm here with a story\",'hello everyone','story about a little',\n"
    "]\n\n"
    "def cleanup_text(text):\n"
    "    if not text: return ''\n"
    "    text = re.sub(r'\\s+', ' ', text.strip())\n"
    "    return text.strip()\n\n"
    "def _is_hallucination(text):\n"
    "    if not text or len(text) < 3: return False\n"
    "    from collections import Counter\n"
    "    counts = Counter(text.replace(' ', ''))\n"
    "    if counts:\n"
    "        ratio = counts.most_common(1)[0][1] / max(len(text.replace(' ', '')), 1)\n"
    "        if ratio > 0.6: return True\n"
    "    lower = text.lower()\n"
    "    if any(lower.startswith(p) or (p in lower and len(text) < 80) for p in HALLUCINATIONS): return True\n"
    "    words = text.split()\n"
    "    if len(words) >= 4 and len(set(w.lower() for w in words)) / len(words) < 0.5: return True\n"
    "    return False\n\n"
    "def _to_wav_bytes(audio):\n"
    "    if not isinstance(audio, np.ndarray):\n"
    "        audio, _ = sf.read(audio, dtype='float32')\n"
    "        if len(audio.shape) > 1: audio = audio.mean(axis=1)\n"
    "    with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp:\n"
    "        sf.write(tmp.name, audio, 16000)\n"
    "        p = tmp.name\n"
    "    data = open(p,'rb').read()\n"
    "    os.unlink(p)\n"
    "    return data\n\n"
    "def _load_audio(x):\n"
    "    if isinstance(x, np.ndarray): return x\n"
    "    a, _ = sf.read(x, dtype='float32')\n"
    "    return a.mean(axis=1) if len(a.shape) > 1 else a\n\n"
    "def _whisper_transcribe(wav_bytes, lang):\n"
    "    try:\n"
    "        r = groq_client.audio.transcriptions.create(\n"
    "            file=('audio.wav', wav_bytes), model=WHISPER_MODEL,\n"
    "            language=lang, response_format='text')\n"
    "        t = r.text if hasattr(r,'text') else str(r)\n"
    "        return cleanup_text(t)\n"
    "    except Exception as e:\n"
    "        print(f'[ASR] transcribe error: {e}')\n"
    "        return ''\n\n"
    "def _llm_call(system_prompt, user_text):\n"
    "    if not user_text: return ''\n"
    "    try:\n"
    "        r = groq_client.chat.completions.create(\n"
    "            model=LLM_MODEL,\n"
    "            messages=[{'role':'system','content':system_prompt},{'role':'user','content':user_text}],\n"
    "            max_tokens=512, temperature=0.1)\n"
    "        return cleanup_text(r.choices[0].message.content.strip())\n"
    "    except Exception as e:\n"
    "        print(f'[ASR] LLM error: {e}')\n"
    "        return ''\n\n"
    "def _to_english(native_text, lang):\n"
    "    result = _llm_call(TRANSLATE_PROMPTS.get(lang, TRANSLATE_PROMPTS['ml']), native_text)\n"
    "    print(f'[ASR] English: {result[:80]}')\n"
    "    return result\n\n"
    "def _to_unicode(native_text, lang):\n"
    "    if not native_text: return ''\n"
    "    ascii_ratio = sum(1 for c in native_text if ord(c)<128)/max(len(native_text),1)\n"
    "    if ascii_ratio < 0.3: return native_text\n"
    "    result = _llm_call(UNICODE_PROMPTS.get(lang, UNICODE_PROMPTS['ml']), native_text)\n"
    "    print(f'[ASR] Unicode fix: {result[:80]}')\n"
    "    return result\n\n"
    "def transcribe_audio(audio_input, style='standard', source_lang='ml'):\n"
    "    try:\n"
    "        wav = _to_wav_bytes(_load_audio(audio_input))\n"
    "        print(f'[ASR] lang={source_lang} bytes={len(wav)}')\n"
    "        native = _whisper_transcribe(wav, source_lang)\n"
    "        print(f'[ASR] Whisper: {native[:80]}')\n"
    "        if _is_hallucination(native): native = ''\n"
    "        english = _to_english(native, source_lang)\n"
    "        native_unicode = _to_unicode(native, source_lang)\n"
    "        print(f'[ASR] Native : {native_unicode[:80]}')\n"
    "        return {'status':'success','text':english,'malayalam_text':native_unicode,\n"
    "                'raw_text':english,'language':source_lang,'segments':[],'device':DEVICE,'model':WHISPER_MODEL}\n"
    "    except Exception as e:\n"
    "        print(f'[ASR] Error: {e}')\n"
    "        return {'status':'failed','error':str(e),'text':'','malayalam_text':'','segments':[]}\n\n"
    "def transcribe_audio_stream(audio_input, style='standard', source_lang='ml'):\n"
    "    try:\n"
    "        wav = _to_wav_bytes(_load_audio(audio_input))\n"
    "        print(f'[ASR] stream lang={source_lang} bytes={len(wav)}')\n"
    "        native = _whisper_transcribe(wav, source_lang)\n"
    "        if _is_hallucination(native): native = ''\n"
    "        print(f'[ASR] Whisper: {native[:80]}')\n"
    "        english = _to_english(native, source_lang)\n"
    "        if english: yield {'type':'english_segment','text':english,'accumulated':english}\n"
    "        native_unicode = _to_unicode(native, source_lang)\n"
    "        print(f'[ASR] Native : {native_unicode[:80]}')\n"
    "        if native_unicode: yield {'type':'malayalam_segment','text':native_unicode,'accumulated':native_unicode}\n"
    "        yield {'type':'complete','english_text':english,'malayalam_text':native_unicode,'language':source_lang,'source_lang':source_lang}\n"
    "    except Exception as e:\n"
    "        print(f'[ASR] Stream Error: {e}')\n"
    "        yield {'type':'error','error':str(e)}\n"
)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Done')